version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - /home/idd_efranco/ambiente/Desenvolvimento/Docker/Volumes/Mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8180:8180
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge